version: '3'
services:
  mysql:
    image: mysql:8.0.27
    restart: always
    container_name: fcmysql
    ports:
      - '20082:4406'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: tyut123456
      # 初始化数据库（后续的初始化 SQL 会在这个库执行）
      MYSQL_DATABASE: fewcode_admin
      MYSQL_USER: user1
      MYSQL_PASSWORD: tyut123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
#  postgresql:
#    image: postgres:14.2
#    restart: always
#    container_name: postgresql
#    ports:
#      - '5432:5432'
#    environment:
#      TZ: Asia/Shanghai
#      POSTGRES_USER: 你的用户名
#      POSTGRES_PASSWORD: 你的用户密码
#      POSTGRES_DB: fewcode_admin
#    volumes:
#      - /docker/postgresql/data/:/var/lib/postgresql/data/
  redis:
    image: redis:6
    restart: always
    container_name: fcredis
    ports:
      - '20083:7789'
    environment:
      TZ: Asia/Shanghai
  fewcode-admin-server:
    build: ./fewcode-admin
    restart: always
    container_name: fewcode-admin-server
    ports:
      - '20080:20080'

    environment:
      TZ: Asia/Shanghai
      DB_HOST: 47.100.198.147
      DB_PORT: 4406
      DB_USER: root
      DB_PWD: tyut123456
      DB_NAME: fewcode_admin
      REDIS_HOST: 47.100.198.147
      REDIS_PORT: 7789
#      REDIS_PWD: 你的 Redis 密码
      REDIS_DB: 3


    volumes:
#      - /docker/fewcode-admin/config/:/app/config/
#      - /docker/fewcode-admin/data/file/:/app/data/file/
#      - /docker/fewcode-admin/logs/:/app/logs/
#      - /docker/fewcode-admin/lib/:/app/lib/
      - /docker/fewcode-admin/bin/fewcode-admin.jar:/app/bin/fewcode-admin.jar

    depends_on:
      - redis
      - mysql


